version: '3.8'
services:
  survey:
    image: hirsc/apsbpinlta.survey
    build:
        context: .
        target: production
        dockerfile: ./Dockerfile
    environment:
        - CLEAN_UP_CRON_TIMING='0 0 * * SUN'
    command: npm run start:prod
    ports:
        - 3001:3001
        - 9229:9229
    volumes:
        - .:/usr/src/app
        - /usr/src/app/node_modules
    restart: unless-stopped