version: "3.6"
networks:
    apsbpinlta:
        driver: bridge
services:
    proxy:
        image: "traefik:v2.5.2"
        ports:
            - "7000:7000" # open this
            - "8080:8080" # traefik ui
        volumes:
            - ./traefik.toml:/etc/traefik/traefik.toml
        # network_mode: host
        extra_hosts:
            - host.docker.internal:172.17.0.1