version: "3.6"
networks:
    apsbpinlta:
        driver: bridge
services:
    proxy:
        image: "traefik:v2.5.2"
        ports:
            - "7000:7000" # open this
            - "9999:9999" # traefik ui
        volumes:
            - ./traefik.toml:/etc/traefik/traefik.toml
        networks:
            - partyplannerpp
        extra_hosts:
            - host.docker.internal:172.19.0.1