defaultEntryPoints = ["http","ws"]

[entryPoints.web]
  address = ":7000"

[entryPoints.websecure]
  address = ":443"

[log]
  level = "DEBUG"
[api]
  debug = true
  insecure = true
  dashboard = true

[web.routers]
  [web.routers.router0]
    rule = "HostRegexp(`{host:.*}`) && PathPrefix(`/`)"
    service = "party-planner-pp"
  [web.routers.router1]
    rule = "HostRegexp(`{host:.*}`) && PathPrefix(`/survey`)"
    service = "survey"

[web.middlewares]
  [web.middlewares.survey-stripPrefix.stripPrefix]
    prefixes = ["/survey"]

[web.services]
  [[web.services.party-planner-pp.loadBalancer.servers]]
    url = "http://host.docker.internal:3006"
  [[web.services.survery.loadBalancer.servers]]
    url = "http://host.docker.internal:3001"