defaultEntryPoints = ["http","ws"]

[entryPoints]
  [entryPoints.web]
    address = ":7000"
  [entryPoints.ws]
    address = ":443"

[providers]
  # Enable the file provider to define routers / middlewares / services in file
  [providers.file]
    directory = "/etc/traefik/config"

[log]
  level = "DEBUG"

[api]
  debug = true
  insecure = true
  dashboard = true