version: "3.8"
services:
  party-planner-pp:
    image: hirsc/apsbpinlta.party-planner-pp
    build:
      context: .
      target: production
  
  party-planner-pp-run:
    build:
      context: .
      target: production
    ports:
      - "3006:3006"
